import {LANGUAGES,getLang,setLang,t,languageOptions} from '../shared/i18n/translations.js';
export const API=String(window.BO_CONFIG?.API_BASE||'/api').replace(/\/$/,'');
export function initLang(){document.querySelectorAll('[data-lang]').forEach(el=>el.innerHTML=languageOptions());document.querySelectorAll('[data-lang]').forEach(el=>el.addEventListener('change',e=>setLang(e.target.value)));document.querySelectorAll('[data-t]').forEach(el=>el.textContent=t(el.dataset.t));document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder));document.documentElement.lang=getLang();document.documentElement.dir=getLang()==='ar'?'rtl':'ltr';}
export function token(){return localStorage.getItem('bo_token')||sessionStorage.getItem('bo_token')}
export function currentUser(){return JSON.parse(localStorage.getItem('bo_user')||sessionStorage.getItem('bo_user')||'null')}
export async function api(path,options={}){const auth=token();const res=await fetch(API+path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{}),...(auth?{Authorization:`Bearer ${auth}`}:{})}});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'Request failed');return data}
export async function apiForm(path,form){const auth=token();const res=await fetch(API+path,{method:'POST',body:JSON.stringify(form),headers:{'Content-Type':'application/json',...(auth?{Authorization:`Bearer ${auth}`}:{})}});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'Request failed');return data}
export function logout(){localStorage.removeItem('bo_token');localStorage.removeItem('bo_user');sessionStorage.removeItem('bo_token');sessionStorage.removeItem('bo_user');location.href='login.html'}
export function guard(role='client'){const u=currentUser();if(!u||u.role!==role){location.href='login.html';return null}return u}
export function nav(active){return `<nav class="bottom-nav"><a class="${active==='home'?'active':''}" href="index.html"><span class="icon">⌂</span><span data-t="home">${t('home')}</span></a><a class="${active==='start'?'active':''}" href="start.html"><span class="icon">▷</span><span data-t="start">${t('start')}</span></a><a class="${active==='history'?'active':''}" href="history.html"><span class="icon">◷</span><span data-t="history">${t('history')}</span></a><a class="${active==='profile'?'active':''}" href="profile.html"><span class="icon">♙</span><span data-t="profile">${t('profile')}</span></a></nav>`}

export async function downloadAttachment(messageId,name='attachment'){const auth=token();const res=await fetch(API+'/messages/file/'+encodeURIComponent(messageId),{headers:{...(auth?{Authorization:`Bearer ${auth}`}:{})}});if(!res.ok){const d=await res.json().catch(()=>({}));throw new Error(d.error||'Could not download attachment')}const blob=await res.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name||'attachment';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
